version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arquisoft
    ports:
      - "5432:5432"
    volumes:
      - ./dataDB/init.sql:/docker-entrypoint-initdb.d/init.sql
